---
title: "Datos de cantones de Costa Rica - flexdashboard + Shiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme:
      version: 3
      bootswatch: cosmo
runtime: shiny       
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r paquetes}
# Carga de paquetes

library(dplyr)
library(sf)
library(DT)
library(ggplot2)
library(plotly)
library(leaflet)
library(shiny)
```

```{r lectura-datos}
# Lectura de datos

cantones <-
  st_read(dsn = "cantones_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```

```{r lista-provincias}
# Lista ordenada de provincias + "Todas"

lista_provincias <- unique(cantones$provincia)
lista_provincias <- sort(lista_provincias)
lista_provincias <- c("Todas", lista_provincias)
```

Column {.sidebar}
-------------------------------------

```{r filtros}
# Filtros de datos


# Encabezado de la columna
h3("Filtros de datos")

# Provincia
selectInput(
  inputId = "provincia",
  label = "Provincia",
  choices = lista_provincias,
  selected = "Todos"
)

# Área
sliderInput(
  "area",
  label = "Área (km2)",
  min = floor(min(cantones$area)),
  max = ceiling(max(cantones$area)),
  value = c(floor(min(cantones$area)), ceiling(max(cantones$area)))
)


# Función para filtrar los datos con base en los controles de entrada
filtrarCantones <- reactive({
  # Valor inicial del objeto que va a retornarse
  cantones_filtrados <- cantones
  
  # Filtrado de cantones por provincia
  if (input$provincia != "Todas") {
    cantones_filtrados <-
      cantones_filtrados %>%
      filter(provincia == input$provincia)
  }
  
  # Filtrado de cantones por área
  cantones_filtrados <-
    cantones_filtrados %>%
    filter(area >= input$area[1] & area <= input$area[2])

  
  return(cantones_filtrados)
})
```

Row {data-height=10}
-----------------------------------------------------------------------

### **Fuente de los datos: [Instituto Geográfico Nacional (IGN)](https://www.snitcr.go.cr/ico_servicios_ogc_info?k=bm9kbzo6MjY=&nombre=IGN%20Cartograf%C3%ADa%201:5mil)**

Row {data-height=590}
-----------------------------------------------------------------------

### Mapa

```{r}
# Mapa


# Paleta de colores
colores_cantones_area <-
  colorNumeric(palette = "Blues",
               domain = cantones$area,
               na.color = "transparent")


renderLeaflet({
  cantones <- filtrarCantones()
  
  leaflet() %>%
    addTiles(group = "OpenStreetMap") %>%
    addPolygons(
      data = cantones,
      fillColor = ~ colores_cantones_area(cantones$area),
      fillOpacity = 0.7,      
      color = "black",
      weight = 1.5,
      popup = paste(
        paste("<a>Cantón:</a>", cantones$canton),
        paste("<a>Área:</a>", cantones$area, "km2"),
        sep = "<br>"
      ),
      group = "Cantones"
    ) %>%
    addLayersControl(baseGroups = c("OpenStreetMap"),
                     overlayGroups = c("Cantones")) %>%
  addLegend(
    # leyenda
    position = "bottomleft",
    pal = colores_cantones_area,
    values = cantones$area,
    group = "Cantones",
    title = "Área (km2)"
  )
})
```

### Tabla

```{r tabla}
# Tabla

renderDT({
  cantones <- filtrarCantones()
  
  cantones %>%
    st_drop_geometry() %>%
    select(provincia, canton, area) %>%
    arrange(desc(area)) %>%
    datatable(
      colnames = c("Provincia", "Cantón", "Área (km2)"),
      options = list(
        pageLength = 5,
        language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
      )
    )
})
```

Row {data-height=400}
-----------------------------------------------------------------------

### Gráfico de cantones con mayor área

```{r grafico}
# Gráfico

renderPlotly({
  cantones <- filtrarCantones()
  
  grafico_ggplot2 <-
    cantones %>%
    st_drop_geometry() %>%
    slice_max(area, n = 20) %>%
    ggplot(aes(x = reorder(canton,-area), y = area)) +
    geom_bar(stat = "identity", fill = "blue") +
    xlab("Cantón") +
    ylab("Área (km2)")
  
  ggplotly(grafico_ggplot2)
})
```

